export const ERROR_MESSAGES = {
    ALL_FIELDS_REQUIRED: 'All Fields are required',
    EMAIL_ALREADY_EXISTS: 'Email  already exists',
    EMAIL_AND_PASSWORD_REQUIRED: 'Email and Password are required',
    USER_NOT_FOUND: 'User not found',
    INVALID_CREDENTIALS: 'Invalid Credentials',
    UNAUTHORIZED_TOKEN_NOT_FOUND: 'Unauthorized - Token not found',
    TOKEN_NOT_FOUND: 'Token not found',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    UNAUTHORIZED_USER: 'Unauthorized - User not found',
    FORBIDDEN_ROLE: 'Forbidden - User does not have the required role',
    TOKEN_NOT_FOUND_OR_EXPIRED: 'Unauthorized - Token not found or expired',
    TOKEN_MISMATCH: 'Unauthorized - Token mismatch',
    INVALID_TOKEN: 'Unauthorized - Invalid token',
    SOMETHING_ERROR: 'Something went wrong',
    FORBIDDEN_ACCESS: 'You do not  have permission to access this',
    INVALID_ROLE: 'Invalid role',
    PLAYER_ALREADY_EXISTS: 'Player already exists',
    PLAYER_NOT_FOUND: 'Player not found',
    PLAYERID_NOT_FOUND: 'PlayerId not found',
    NO_OWNERS_FOUND: 'No Owners found',
    TEAM_NAME_ALREADY_EXISTS: 'Team name already exists',
    NO_TEAM_FOUND: 'No Team found',
    ALREADY_ASSIGNED_TO_OWNER: 'Team is already assigned to an owner',
    TOURNAMENT_OVERLAPPED: 'Tournament Overlapped',
    NO_TOURNAMENT_FOUND: 'No Tournament found',
    AUCTION_NOT_FOUND: 'Auction not found',
    INVALID_STATUS: 'Invalid status',
    NO_BID_FOUND: 'No Bid found',
    NO_LIVE_AUCTION_FOUND: 'No Live auction found',
    AUCTION_ALREADY_ENDED: 'Auction already ended',
    NO_HIGHEST_BID_FOUND: 'No auction bid found',
    FILE_REQUIRED: 'File is required',
    PROFILE_UPLOAD_FAILED: 'Profile upload failed',
    TEAMS_NOT_FOUND: 'No Teams found',
    NO_TEAMS_FOUND_IN_TOURNAMENT: 'No Teams found in tournament',
    NO_BID_HISTORY_FOUND: 'No bid history found',
    EXPORTED_DATA_NOT_FOUND: 'Exported data not found',
    FILE_DOWNLOAD_ERROR: 'Error downloading file'
  };
  
  export const SUCCESS_MESSAGES = {
    USER_REGISTERED_SUCCESSFULLY: 'User Registered successfully',
    USER_LOGIN_SUCCESSFULLY: 'User Login Successfully',
    USER_LOGOUT_SUCCESSFULLY: 'User Logout Successfully',
    PLAYER_REGISTER_SUCCESSFULLY: 'Player Register Successfully',
    ALL_PLAYERS_FETCHED_SUCCESSFULLY: 'All Players Fetched Successfully',
    PLAYER_DETAILS_FETCHED_SUCCESSFULLY: 'Player Details Fetched Successfully',
    PLAYER_DETAILS_UPDATED_SUCCESSFULLY: 'Player Details Updated Successfully',
    PLAYER_DELETED_SUCCESSFULLY: 'Player Deleted Successfully',
    OWNER_REGISTRATION: 'Owner Registered Successfully',
    OWNERS_FETCHED_SUCCESSFULLY: 'Owners Fetched Successfully',
    OWNER_DETAILS_FETCHED_SUCCESSFULLY: 'Owner Details Fetched Successfully',
    OWNER_DETAILS_UPDATED_SUCCESSFULLY: 'Owner Details Updated Successfully',
    OWNER_DELETED_SUCCESSFULLY: 'Owner Deleted Successfully',
    TEAM_ASSIGNED_SUCCESSFULLY: 'Team Assigned Successfully',
    TOURNAMENT_CREATED_SUCCESSFULLY: 'Tournament Created Successfully',
    TOURNAMENT_FETCHED_SUCCESSFULLY: 'Tournament Fetched Successfully',
    TOURNAMENT_DETAILS_FETCHED_SUCCESSFULLY: 'Tournament Details Fetched Successfully',
    TOURNAMENT_UPDATED_SUCCESSFULLY: 'Tournament Updated Successfully',
    TOURNAMENT_DELETED_SUCCESSFULLY: 'Tournament Deleted Successfully',
    OWNER_POINTS_UPDATED_SUCCESSFULLY: 'Owner Points Updated Successfully', 
    AUCTION_START_SUCCESSFULLY: 'Auction Started Successfully',
    BID_PLACED_SUCCESSFULLY: 'Bid Placed Successfully',
    BID_STATUS_UPDATED_SUCCESSFULLY: 'Bid Status Updated Successfully',
    BIDS_FETCHED_SUCCESSFULLY: 'Bids Fetched Successfully',
    AUCTION_END_SUCCESSFULLY: 'Auction End Successfully',
    AUCTION_DETAILS_FETCHED: 'Auction Details Fetched Success',
    TOP_BIDDERS_FETCHED: 'Top Bidder Details Fetched Success',
    TEAM_CREATED_SUCCESSFULLY: 'Team Created Successfully',
    PROFILE_UPLOAD_SUCCESSFULLY: 'Profile Upload Successfully',
    TEAMS_FETCHED_SUCCESSFULLY: 'Teams Fetched Successfully',
    TEAM_DETAILS_FETCHED_SUCCESSFULLY: 'Team Details Fetched Successfully',
    TEAM_DETAILS_UPDATED_SUCCESSFULLY: 'Team Details Updated Successfully',
    TEAM_DELETED_SUCCESSFULLY: 'Team Deleted Successfully',
    PLAYER_ADDED_TO_TEAM_SUCCESSFULLY: 'Player Added to Team Successfully',
    TEAMS_ADDED_TO_TOURNAMENT: 'Teams Added to Tournament Successfully',
    TEAM_TOURNAMENT_UPDATED_SUCCESSFULLY: 'Team Tournament Updated Successfully',
    ADMIN_STATISTICS_FETCHED_SUCCESSFULLY: 'Admin Statistics Fetched Successfully',
    BID_HISTORY_RETRIEVED: 'Bid History Fetched Successfully',
    BID_HISTORY_CREATED_SUCCESSFULLY: 'Bid History Created Successfully',
    AUCTION_EXPORT_SUCCESS: 'Auction Exported Successfully',
    
  };